var GAME_LEVELS = [
  ["                                                                                                                         ",
   "                                                                                                                         ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "     xx                        xx!!!!!xx                     xx!!!!!!xx       x      x               xxxxxxxx            ",
   "    xx                         xx!!!!xx                      xx!!!!xx                                       xxxxx        ",
   "    x                           xxxxx                         xx!!xx                                          xxx        ",
   "    x                                                          x!!x                                              xx      ",
   "    x                                                          xxxx                                               xx     ",
   "    x                                                           v                                               xx     ",
   "    x                                                                     xx!!xxx!!xx                              xx    ",
   "    x                                                                     xxxxxxxxx       xxxxxxxx                  x   ",
   "    x                                 xxxxxxxx                                                                       x   ",
   "    x                                                                         !!!!!!!!!!!                            x   ",
   "    x                                                                  x     !!xx!!!!!xx!!!                         x   ",
   "    x                                                                   x   !!xx!!!!!!!xx!!!                    xxxxxx   ",
   "    x                                                                   x !!!xx!!!!!!!!!xx!!!!                 xx        ",
   "    x                                                                  xx!!xx!!!!!!!!!!!xx!!!!               xx         ",
   "    x    @       o                                    xxxxxxx           !!!!!xx!!!!!!!!!!!!!xx!!!              xx         ",
   "    x    xx      xxx|                           xxxxxxxxxxxxxxxxx  !!!!!!!xx!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!xxx          ",
   "    xxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                   xx!!!!!!!!!xxx                                                                                        ",
   "                    xx!!!!!!!!xx                                                                                         ",
   "                     xx!!!!!!xx                                                                                          ",
   "                       xxxxxx                                                                                            "],
  ["x                                                                                                                                                                ",
   "x                                                                                                                                                                ",
   "x                                                                                                                                                                ",
   "x|                                                                                                                                                               ",
   "x                                                                                                                                                                ",
   "x                                                      o                                                                                                         ",
   "x|                                                 xxxxxx                                                                                                        ",
   "x                                         xxxxxx                                                                                                                 ",
   "x                                xxxx                                                                                                                            ",
   "x|                     xxxx                                                                                                                                      ",
   "x           xx                                                                                                                                                   ",
   "x           xxxxxxxx                                                                                                                                             ",
   "x|                xxxxxxxxx                                                                                                                                      ",
   "x                        xxxxxxxxx                        o                                                                  o                                   ",
   "x                               xxxxxxxx             xxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxx            xx         xxxxxxx                                ",
   "x|                                    xxxx            v         v             xxx                               x                                                ",
   "x                                       xxxx                                 xxxx                               x                                                ",
   "x                                          xxxx                            xxxx                                 x                                                ",
   "x|                                           xxx                         xxxx                                   x                                                ",
   "x                                              xxx           o          xxxx                                   xx                                                ",
   "x                                               xxxxxxxxxxxxxxxxxxxxxxxxx                                       x                                                ",
   "x|                                                                                                              x                                                ",
   "x                                                                                                               x                                                ",
   "x                                                                                                           xxxxx                                                ",
   "x|                                                                                                        xxxx                                                   ",
   "x                                                                                                       xxxx                                                     ",
   "x                                        xxxx        xxxxx                 x=   o      x              xxxx                                                       ",
   "x|                                     xxxx             xxxxx              xxxxxxxxxxxxx           xxxxxx                                                        ",
   "x                                     xxxx    x            xxxxx                                 xxxx                                                            ",
   "x                                    xxxx                     xxxxx                           xxxxx                                                              ",
   "x|                                  xxx            x            xxxxxx=          o          xxxxx                                                                ",
   "x                                oxxxx                             xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                   ",
   "x                               xxxx        x                                                                                                                    ",
   "x|                            xxxxx                                                                                                                              ",
   "x                           xxxx                   x                                                                                                             ",
   "x                         xxxx            x                                                                                                                      ",
   "x|                     oxxxx                                                                                                                                     ",
   "x                      xxxxx                   k                                                                                                                 ",
   "x  @                xxxxxx             xxxxxxxxxxxxxx                                                                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    v                 v             v              v       v             v           v       v     v       v      v     v    ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                   o                   xxxxx                 ",
   "                xxxxxxx     xxxxx        x|                    x        x     xxxxxxxxxxxx                 xx                ",
   "                      x!   !x            x          k          x        x|                                  xx               ",
   "                      x!   !x            x       xxxxxxx       x        x                  xxxxxxx           xx              ",
   "                      x!   !x            x                     x        x                                     xx             ",
   "                      x!   !x            x|                    x        x|                                    xx             ",
   "                      x!   !x            x    x                x        x                                    xx              ",
   "                      x!   !x            x                x    x        x                       xx          xx               ",
   "                      x! o !x            x|                             x|                       xx    o   xx                ",
   "                      x     x            x                                         x=       x    xxxxxxxxxx                  ",
   "                                         x                                         xxxxxxxxxx                                ",
   "                                         xxxxxxxxxxxxxxxxxxxxxx                     v      v                                 ",
   "                                                                                                                             ",
   "                                                                   xxxxxx                                                    ",
   "                                                                      v                                                      ",
   "                                                                                                                             ",
   "                                                                               xxxxxx                                        ",
   "                                                       xxxx                                                                  ",
   "   o                                                                                                                         ",
   "  xxx=      x=         x=         x=        x                                                                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        xxx                    xx                               ",
   "                                            xx                      xx xx|                 xx                                ",
   "                                             xx                    xx   xx                xx        xxxxxxxx                 ",
   "                                              xx                  xx     xx|             xx                                  ",
   "                                               xx                xx       xx            xx                                   ",
   "                                                xx              xx         xx|         xx         o        xxxxxxxx          ",
   "                                                 xx      @     xx           xx   o    xx       xxxxxxxx                      ",
   "                                                  xxxxxxxxxxxxxx             xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["x       x     xxxx    x    x                                                                                  ",
   " x     x     x    x   x    x                                                                                  ",
   "  x   x     x      x  x    x                                                                                  ",
   "   x x     x        x x    x                                                                                  ",
   "    x      x        x x    x                                                                                  ",
   "    x       x      x  x    x                                                                                  ",
   "    x        x    x   x    x                                                                                  ",
   "    x         xxxx    xxxxxx                                                                                  ",
   "                                                                                                              ",
   " x     x     x   x  xx   x                                                                                    ",
   "  x   x x   x       x x  x                                                                                    ",
   "   x x   x x     x  x  x x                                                                                    ",
   "    x     x      x  x   xx                                                                                    ",
   "                                                                                                              ",
   "          x       x                                                                                           ",
   "          x       x                                                                                           ",
   "                                                                                                              ",
   "      x               x                                                                                       ",
   "      x               x                                                                                       ",
   "      x               x                                                                                       ",
   "      xxxxxxxxxxxxxxxxx                                                                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
